
LANGUAGES = {
    'aa' : 'Afar',
    'ab' : 'Abjaso',
    'ace' : 'Achenés',
    'ach' : 'Acholi',
    'ada' : 'Adangme',
    'af' : 'Afrikáans',
    'afh' : 'Afrihili',
    'aka' : 'Acano',
    'akk' : 'Acadio',
    'ale' : 'Aleutiano',
    'am' : 'Amárico',
    'an' : 'Aragonés',
    'ang' : 'Inglés antiguo',
    'ar' : 'Árabe',
    'arc' : 'Arameo',
    'ars' : 'Árabe najdi',
    'arn' : 'Mapuche',
    'arp' : 'Arapaho',
    'art' : 'Artificial',
    'arw' : 'Arawak',
    'as' : 'Asamés',
    'ast' : 'Asturiano',
    'ava' : 'Avar',
    'ave' : 'Avéstico',
    'awa' : 'Awadhi',
    'ay' : 'Aimara',
    'az' : 'Azerí',
    'ba' : 'Baskir',
    'bal' : 'Baluchi',
    'bam' : 'Bambara',
    'ban' : 'Balinés',
    'bas' : 'Basa',
    'be' : 'Bielorruso',
    'bej' : 'Beya',
    'bem' : 'Bemba',
    'bg' : 'Búlgaro',
    'bh' : 'Bihari',
    'bho' : 'Bhojpuri',
    'bi' : 'Bislama',
    'bik' : 'Bicolano',
    'bin' : 'Edo',
    'bla' : 'Pie negro',
    'bn' : 'Bengalí',
    'bo' : 'Tibetano',
    'br' : 'Bretón',
    'bra' : 'Brijbhasha',
    'bs' : 'Bosnio',
    'bua' : 'Buriato',
    'bug' : 'Buguinés',
    'ca' : 'Catalán',
    'cad' : 'Caddo',
    'car' : 'Taíno',
    'ceb' : 'Cebuano',
    'ch' : 'Chamorro',
    'cha' : 'Chamorro',
    'chb' : 'Chibcha',
    'che' : 'Checheno',
    'chg' : 'Chagatay',
    'chm' : 'Mari',
    'cmn' : 'Mandarín',
    'cho' : 'Choctaw',
    'chr' : 'Cheroqui',
    'chu' : 'Eslavo eclesiástico antiguo',
    'chv' : 'Chuvasio',
    'chy' : 'Cheyene',
    'co' : 'Corso',
    'cr' : 'Cree',
    'cop' : 'Copto',
    'cor' : 'Córnico',
    'crh' : 'Tártaro de Crimea',
    'cre' : 'Cree',
    'cs' : 'Checo',
    'csb' : 'Casubio',
    'cy' : 'Galés',
    'da' : 'Danés',
    'dak' : 'Dakota',
    'de' : 'Alemán',
    'del' : 'Delaware',
    'din' : 'Dinka',
    'diu' : 'Diriku',
    'div' : 'Dhivehi',
    'doi' : 'Dogri',
    'dua' : 'Duala',
    'dum' : 'Neerlandés medio',
    'dyu' : 'Diula',
    'dz' : 'Dzongkha',
    'efi' : 'Efik',
    'egy' : 'Egipcio antiguo',
    'eka' : 'Acayo',
    'el' : 'Griego',
    'elx' : 'Elamita',
    'en' : 'Inglés',
    'enm' : 'Inglés medio',
    'eo' : 'Esperanto',
    'es' : 'Español',
    'eso' : 'Lengua de señas de Estonia',
    'et' : 'Estonio',
    'eu' : 'Euskera',
    'ewe' : 'Ewe',
    'ewo' : 'Ewondo',
    'fa' : 'Persa',
    'fan' : 'Fang',
    'fat' : 'Fante',
    'fi' : 'Finés',
    'fj' : 'Fiyiano',
    'fo' : 'Feroés',
    'fr' : 'Francés',
    'frm' : 'Francés medio',
    'fro' : 'Francés antiguo',
    'ful' : 'Fula',
    'fur' : 'Friulano',
    'fy' : 'Frisón',
    'ga' : 'Irlandés',
    'gaa' : 'Ga',
    'gay' : 'Gayo',
    'gd' : 'Gaélico escocés',
    'gez' : 'Yehén',
    'gil' : 'Kiribasiano',
    'gl' : 'Gallego',
    'gmh' : 'Alemán medio',
    'gn' : 'Guaraní',
    'goh' : 'Alemán antiguo',
    'gon' : 'Gondi',
    'got' : 'Gótico',
    'grb' : 'Grebo',
    'grc' : 'Griego antiguo',
    'gu' : 'Guyaratí',
    'gv' : 'Manés',
    'ha' : 'Hausa',
    'hai' : 'Haida',
    'haw' : 'Hawaiano',
    'he' : 'Hebreo',
    'her' : 'Herero',
    'hi' : 'Hindi',
    'hil' : 'Hiligaynon',
    'hmo' : 'Hiri motu',
    'hr' : 'Croata',
    'hu' : 'Húngaro',
    'hup' : 'Hupa',
    'hy' : 'Armenio',
    'ia' : 'Interlingua',
    'iba' : 'Dayaco',
    'ibo' : 'Plantilla:ibo',
    'id' : 'Indonesio',
    'ie' : 'Occidental',
    'ii' : 'Lolo de Sichuán',
    'ik' : 'Inupiaq',
    'ilo' : 'Ilocano',
    'io' : 'Ido',
    'is' : 'Islandés',
    'it' : 'Italiano',
    'iu' : 'Inuktitut',
    'ja' : 'Japonés',
    'jpr' : 'Judeopersa',
    'jrb' : 'Judeoárabe',
    'jv' : 'Javanés',
    'ka' : 'Georgiano',
    'kaa' : 'Karakalpako',
    'kab' : 'Cabil',
    'kac' : 'Kachín',
    'kam' : 'Kikamba',
    'kau' : 'Plantilla kau',
    'kaw' : 'Cavi',
    'kha' : 'Jasí',
    'kho' : 'Jotanés',
    'kik' : 'Plantilla kik',
    'kk' : 'Kazajo',
    'kl' : 'Groenlandés',
    'km' : 'Camboyano',
    'kn' : 'Kannada',
    'ko' : 'Coreano',
    'kok' : 'Konkani',
    'kom' : 'Plantilla kom',
    'kon' : 'Plantilla kon',
    'kos' : 'Kosraeano',
    'kpe' : 'Kpelle',
    'kru' : 'Curuj',
    'ks' : 'Cachemiro',
    'ku' : 'Kurdo',
    'kua' : 'Plantilla kua',
    'kum' : 'Kumyko',
    'kus' : 'Kusaal',
    'kut' : 'Kutenai',
    'kv' : 'Komi',
    'kw' : 'Córnico',
    'ky' : 'Kirguís',
    'la' : 'Latín',
    'lad' : 'Judeoespañol',
    'lah' : 'Landi',
    'lam' : 'Lamba',
    'lb' : 'Luxemburgués',
    'lez' : 'Lesguiano',
    'li' : 'Limburgués',
    'ln' : 'Lingala',
    'lo' : 'Lao',
    'lt' : 'Lituano',
    'lv' : 'Letón',
    'mdf' : 'Moksha',
    'mi' : 'Maorí',
    'mk' : 'Macedonio',
    'ml' : 'Malayalam',
    'mn' : 'Mongol',
    'mnc' : 'Manchú',
    'mo' : 'Moldavo',
    'mr' : 'Maratí',
    'ms' : 'Malayo',
    'mt' : 'Maltés',
    'my' : 'Birmano',
    'myv' : 'Erzya',
    'na' : 'Nauruano',
    'nah' : 'Náhuatl (realmente es de ISO 639-2 pero la fundación Wikimedia lo usa)',
    'nap' : 'Napolitano',
    'nav' : 'Plantilla:nav',
    'nb' : 'Noruego bokmål',
    'ne' : 'Nepalés',
    'nd' : 'Sindebele',
    'nds' : 'Bajo sajón',
    'nds-nl' : 'Bajo sajón neerlandés',
    'ng' : 'Ndonga',
    'nl' : 'Neerlandés',
    'nn' : 'Noruego nynorsk',
    'no' : 'Noruego bokmål',
    'nr' : 'Nrebele',
    'nv' : 'Navajo',
    'ny' : 'Chewa',
    'oc' : 'Occitano',
    'oj' : 'Ojibwe',
    'om' : 'Oromo',
    'or' : 'Oriya',
    'os' : 'Oseta',
    'pap' : 'Papiamento',
    'pi' : 'Pali',
    'pl' : 'Polaco',
    'ps' : 'Pastún',
    'pt' : 'Portugués',
    'qu' : 'Quechua',
    'rap' : 'Rapa nui',
    'rn' : 'Kirundi',
    'ro' : 'Rumano',
    'ru' : 'Ruso',
    'rw' : 'Ruandés',
    'sa' : 'Sánscrito',
    'sc' : 'Sardo',
    'sco' : 'Escocés',
    'sd' : 'Sindhi',
    'si' : 'Cingalés',
    'se' : 'Sami septentrional',
    'sk' : 'Eslovaco',
    'sl' : 'Esloveno',
    'sm' : 'Samoano',
    'smn' : 'Sami inari',
    'sn' : 'Shona',
    'so' : 'Somalí',
    'sq' : 'Albanés',
    'sr' : 'Serbio',
    'ss' : 'Swazi',
    'su' : 'Sundanés',
    'sv' : 'Sueco',
    'sw' : 'Swahili',
    'ta' : 'Tamil',
    'te' : 'Telugú',
    'tg' : 'Tayiko',
    'th' : 'Tailandés',
    'ti' : 'Tigriña',
    'tk' : 'Turcomano',
    'tl' : 'Tagalo',
    'tlh' : 'Klingon',
    'tn' : 'Setsuana',
    'to' : 'Tongano',
    'tpi' : 'Tok pisin',
    'tr' : 'Turco',
    'ts' : 'Xitsonga',
    'tt' : 'Tártaro',
    'tw' : 'Twi',
    'udm' : 'Udmurto',
    'ug' : 'Uigur',
    'uk' : 'Ucraniano',
    'ur' : 'Urdu',
    'uz' : 'Uzbeco',
    've' : 'Luvenda',
    'vi' : 'Vietnamita',
    'vo' : 'Volapuk',
    'vot' : 'Votio',
    'wa' : 'Valón',
    'wo' : 'Wolof',
    'xh' : 'Xhosa',
    'yi' : 'Yídish',
    'yo' : 'Yoruba',
    'yua' : 'Maya yucateco',
    'yue' : 'Cantonés',
    'za' : 'Chuan',
    'zh' : 'Mandarín',
    'zu' : 'Zulú'
	}