# -*- coding: UTF-8 -*-
LANGUAGES = {
    u'aa' : u'Afar',
    u'ab' : u'Abjaso',
    u'ace' : u'Achenés',
    u'ach' : u'Acholi',
    u'ada' : u'Adangme',
    u'af' : u'Afrikáans',
    u'afh' : u'Afrihili',
    u'aka' : u'Acano',
    u'akk' : u'Acadio',
    u'ale' : u'Aleutiano',
    u'am' : u'Amárico',
    u'an' : u'Aragonés',
    u'ang' : u'Inglés antiguo',
    u'ar' : u'Árabe',
    u'arc' : u'Arameo',
    u'ars' : u'Árabe najdi',
    u'arn' : u'Mapuche',
    u'arp' : u'Arapaho',
    u'art' : u'Artificial',
    u'arw' : u'Arawak',
    u'as' : u'Asamés',
    u'ast' : u'Asturiano',
    u'ava' : u'Avar',
    u'ave' : u'Avéstico',
    u'awa' : u'Awadhi',
    u'ay' : u'Aimara',
    u'az' : u'Azerí',
    u'ba' : u'Baskir',
    u'bal' : u'Baluchi',
    u'bam' : u'Bambara',
    u'ban' : u'Balinés',
    u'bas' : u'Basa',
    u'be' : u'Bielorruso',
    u'bej' : u'Beya',
    u'bem' : u'Bemba',
    u'bg' : u'Búlgaro',
    u'bh' : u'Bihari',
    u'bho' : u'Bhojpuri',
    u'bi' : u'Bislama',
    u'bik' : u'Bicolano',
    u'bin' : u'Edo',
    u'bla' : u'Pie negro',
    u'bn' : u'Bengalí',
    u'bo' : u'Tibetano',
    u'br' : u'Bretón',
    u'bra' : u'Brijbhasha',
    u'bs' : u'Bosnio',
    u'bua' : u'Buriato',
    u'bug' : u'Buguinés',
    u'ca' : u'Catalán',
    u'cad' : u'Caddo',
    u'car' : u'Taíno',
    u'ceb' : u'Cebuano',
    u'ch' : u'Chamorro',
    u'cha' : u'Chamorro',
    u'chb' : u'Chibcha',
    u'che' : u'Checheno',
    u'chg' : u'Chagatay',
    u'chm' : u'Mari',
    u'cmn' : u'Mandarín',
    u'cho' : u'Choctaw',
    u'chr' : u'Cheroqui',
    u'chu' : u'Eslavo eclesiástico antiguo',
    u'chv' : u'Chuvasio',
    u'chy' : u'Cheyene',
    u'co' : u'Corso',
    u'cr' : u'Cree',
    u'cop' : u'Copto',
    u'cor' : u'Córnico',
    u'crh' : u'Tártaro de Crimea',
    u'cre' : u'Cree',
    u'cs' : u'Checo',
    u'csb' : u'Casubio',
    u'cy' : u'Galés',
    u'da' : u'Danés',
    u'dak' : u'Dakota',
    u'de' : u'Alemán',
    u'del' : u'Delaware',
    u'din' : u'Dinka',
    u'diu' : u'Diriku',
    u'div' : u'Dhivehi',
    u'doi' : u'Dogri',
    u'dua' : u'Duala',
    u'dum' : u'Neerlandés medio',
    u'dyu' : u'Diula',
    u'dz' : u'Dzongkha',
    u'efi' : u'Efik',
    u'egy' : u'Egipcio antiguo',
    u'eka' : u'Acayo',
    u'el' : u'Griego',
    u'elx' : u'Elamita',
    u'en' : u'Inglés',
    u'enm' : u'Inglés medio',
    u'eo' : u'Esperanto',
    u'es' : u'Español',
    u'eso' : u'Lengua de señas de Estonia',
    u'et' : u'Estonio',
    u'eu' : u'Euskera',
    u'ewe' : u'Ewe',
    u'ewo' : u'Ewondo',
    u'fa' : u'Persa',
    u'fan' : u'Fang',
    u'fat' : u'Fante',
    u'fi' : u'Finés',
    u'fj' : u'Fiyiano',
    u'fo' : u'Feroés',
    u'fr' : u'Francés',
    u'frm' : u'Francés medio',
    u'fro' : u'Francés antiguo',
    u'ful' : u'Fula',
    u'fur' : u'Friulano',
    u'fy' : u'Frisón',
    u'ga' : u'Irlandés',
    u'gaa' : u'Ga',
    u'gay' : u'Gayo',
    u'gd' : u'Gaélico escocés',
    u'gez' : u'Yehén',
    u'gil' : u'Kiribasiano',
    u'gl' : u'Gallego',
    u'gmh' : u'Alemán medio',
    u'gn' : u'Guaraní',
    u'goh' : u'Alemán antiguo',
    u'gon' : u'Gondi',
    u'got' : u'Gótico',
    u'grb' : u'Grebo',
    u'grc' : u'Griego antiguo',
    u'gu' : u'Guyaratí',
    u'gv' : u'Manés',
    u'ha' : u'Hausa',
    u'hai' : u'Haida',
    u'haw' : u'Hawaiano',
    u'he' : u'Hebreo',
    u'her' : u'Herero',
    u'hi' : u'Hindi',
    u'hil' : u'Hiligaynon',
    u'hmo' : u'Hiri motu',
    u'hr' : u'Croata',
    u'hu' : u'Húngaro',
    u'hup' : u'Hupa',
    u'hy' : u'Armenio',
    u'ia' : u'Interlingua',
    u'iba' : u'Dayaco',
    u'ibo' : u'Plantilla:ibo',
    u'id' : u'Indonesio',
    u'ie' : u'Occidental',
    u'ii' : u'Lolo de Sichuán',
    u'ik' : u'Inupiaq',
    u'ilo' : u'Ilocano',
    u'io' : u'Ido',
    u'is' : u'Islandés',
    u'it' : u'Italiano',
    u'iu' : u'Inuktitut',
    u'ja' : u'Japonés',
    u'jpr' : u'Judeopersa',
    u'jrb' : u'Judeoárabe',
    u'jv' : u'Javanés',
    u'ka' : u'Georgiano',
    u'kaa' : u'Karakalpako',
    u'kab' : u'Cabil',
    u'kac' : u'Kachín',
    u'kam' : u'Kikamba',
    u'kau' : u'Plantilla kau',
    u'kaw' : u'Cavi',
    u'kha' : u'Jasí',
    u'kho' : u'Jotanés',
    u'kik' : u'Plantilla kik',
    u'kk' : u'Kazajo',
    u'kl' : u'Groenlandés',
    u'km' : u'Camboyano',
    u'kn' : u'Kannada',
    u'ko' : u'Coreano',
    u'kok' : u'Konkani',
    u'kom' : u'Plantilla kom',
    u'kon' : u'Plantilla kon',
    u'kos' : u'Kosraeano',
    u'kpe' : u'Kpelle',
    u'kru' : u'Curuj',
    u'ks' : u'Cachemiro',
    u'ku' : u'Kurdo',
    u'kua' : u'Plantilla kua',
    u'kum' : u'Kumyko',
    u'kus' : u'Kusaal',
    u'kut' : u'Kutenai',
    u'kv' : u'Komi',
    u'kw' : u'Córnico',
    u'ky' : u'Kirguís',
    u'la' : u'Latín',
    u'lad' : u'Judeoespañol',
    u'lah' : u'Landi',
    u'lam' : u'Lamba',
    u'lb' : u'Luxemburgués',
    u'lez' : u'Lesguiano',
    u'li' : u'Limburgués',
    u'ln' : u'Lingala',
    u'lo' : u'Lao',
    u'lt' : u'Lituano',
    u'lv' : u'Letón',
    u'mdf' : u'Moksha',
    u'mi' : u'Maorí',
    u'mk' : u'Macedonio',
    u'ml' : u'Malayalam',
    u'mn' : u'Mongol',
    u'mnc' : u'Manchú',
    u'mo' : u'Moldavo',
    u'mr' : u'Maratí',
    u'ms' : u'Malayo',
    u'mt' : u'Maltés',
    u'my' : u'Birmano',
    u'myv' : u'Erzya',
    u'na' : u'Nauruano',
    u'nah' : u'Náhuatl',
    u'nap' : u'Napolitano',
    u'nav' : u'Plantilla:nav',
    u'nb' : u'Noruego bokmål',
    u'ne' : u'Nepalés',
    u'nd' : u'Sindebele',
    u'nds' : u'Bajo sajón',
    u'nds-nl' : u'Bajo sajón neerlandés',
    u'ng' : u'Ndonga',
    u'nl' : u'Neerlandés',
    u'nn' : u'Noruego nynorsk',
    u'no' : u'Noruego bokmål',
    u'nr' : u'Nrebele',
    u'nv' : u'Navajo',
    u'ny' : u'Chewa',
    u'oc' : u'Occitano',
    u'oj' : u'Ojibwe',
    u'om' : u'Oromo',
    u'or' : u'Oriya',
    u'os' : u'Oseta',
    u'pap' : u'Papiamento',
    u'pi' : u'Pali',
    u'pl' : u'Polaco',
    u'ps' : u'Pastún',
    u'pt' : u'Portugués',
    u'qu' : u'Quechua',
    u'rap' : u'Rapa nui',
    u'rn' : u'Kirundi',
    u'ro' : u'Rumano',
    u'ru' : u'Ruso',
    u'rw' : u'Ruandés',
    u'sa' : u'Sánscrito',
    u'sc' : u'Sardo',
    u'sco' : u'Escocés',
    u'sd' : u'Sindhi',
    u'si' : u'Cingalés',
    u'se' : u'Sami septentrional',
    u'sk' : u'Eslovaco',
    u'sl' : u'Esloveno',
    u'sm' : u'Samoano',
    u'smn' : u'Sami inari',
    u'sn' : u'Shona',
    u'so' : u'Somalí',
    u'sq' : u'Albanés',
    u'sr' : u'Serbio',
    u'ss' : u'Swazi',
    u'su' : u'Sundanés',
    u'sv' : u'Sueco',
    u'sw' : u'Swahili',
    u'ta' : u'Tamil',
    u'te' : u'Telugú',
    u'tg' : u'Tayiko',
    u'th' : u'Tailandés',
    u'ti' : u'Tigriña',
    u'tk' : u'Turcomano',
    u'tl' : u'Tagalo',
    u'tlh' : u'Klingon',
    u'tn' : u'Setsuana',
    u'to' : u'Tongano',
    u'tpi' : u'Tok pisin',
    u'tr' : u'Turco',
    u'ts' : u'Xitsonga',
    u'tt' : u'Tártaro',
    u'tw' : u'Twi',
    u'udm' : u'Udmurto',
    u'ug' : u'Uigur',
    u'uk' : u'Ucraniano',
    u'ur' : u'Urdu',
    u'uz' : u'Uzbeco',
    u've' : u'Luvenda',
    u'vi' : u'Vietnamita',
    u'vo' : u'Volapuk',
    u'vot' : u'Votio',
    u'wa' : u'Valón',
    u'wo' : u'Wolof',
    u'xh' : u'Xhosa',
    u'yi' : u'Yídish',
    u'yo' : u'Yoruba',
    u'yua' : u'Maya yucateco',
    u'yue' : u'Cantonés',
    u'za' : u'Chuan',
    u'zh' : u'Mandarín',
    u'zu' : u'Zulú'
	}